### ISSUE TITLE
JAVA 8  - Monitor - CPU usage: <unknown> 

### ISSUE THREAD

**Issue by gknepper** [veithen/visualwas#4]
When using Java 8 monitor doesn't show the cpu usage, only the GC activity.

Thanks in advance.

**Comment by veithen** [comment]
It looks like this depends on the existence of the (non standard) `getProcessCpuLoad` method on the `OperatingSystemMXBean` implementation (see https://stackoverflow.com/questions/3044841/cpu-usage-mbean-on-sun-jvm). In OpenJ9, that method no longer exists: https://github.com/eclipse/openj9/blob/master/jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/OperatingSystemMXBeanImpl.java.

**Comment by veithen** [comment]
Confirmed this by looking at a JRE that comes with WebSphere 9.

There is not much that can be done, except maybe finding a different way to get that information and wrap the MXBean provided by the JRE to plumb that metric through in such a way that VisualVM finds it where it expects it.

**Comment by gknepper** [comment]
Just a idea... I'm not sure how hard is implement this. IBM provides jvmObj.getStatistic('ProcessCpuUsage').getCount() in PMI. Maybe write a wrapper to this PMI method can deal with this issue. 

Thanks in advance.

**Comment by veithen** [comment]
For my own reference, here's a code example showing how to access PMI stats locally: https://www.ibm.com/developerworks/community/forums/html/topic?id=51379efb-58ee-4504-8813-963470fdfa73.
