### ISSUE TITLE
Visual GC dashboard implementation

### ISSUE THREAD

**Issue by gknepper** [veithen/visualwas#6]
Hi,

I don't know how hard it is.. but are you planning implement the Visual GC dashboard to visualwas plugin? 

Thanks,

**Comment by veithen** [comment]
I think that Visual GC is actually designed specifically for Oracle HotSpot VMs and wouldn't work with IBM Java.

**Comment by gknepper** [comment]
Do you think this can't be implemented using PMI metrics ? Sorry post again...

**Comment by veithen** [comment]
That would probably be a large effort.
