### ISSUE TITLE
Does not work with VisualVM >= 2.0

### ISSUE THREAD

**Issue by cmoetzing** [veithen/visualwas#7]
Unfortunately the plugin is not installable in VisualVM >= 2.0.

**Comment by veithen** [comment]
That's not very surprising; they changed all package names from `com.sun.tools` to `org.graalvm`: https://github.com/oracle/visualvm/commit/affe1eb1308554d4df8fcdd6308e9fa4e3f3787a.

**Comment by veithen** [comment]
I just published release 4.0.0 which seems to work well with VisualVM 2.0.1.
